### ISSUE TITLE
Open parquet file with `vds3` fails

### ISSUE THREAD

**Issue by spren9er** [ajkerrigan/visidata-plugins#27]
When I try to open parquet files from AWS S3, I always get following error message:

```
ArrowInvalid: Expected a local filesystem path, got a URI: 's3:/<bucket-name>/<filename>.parquet'
```

Tried with VisiData v2.10.1 and 2.11 along with different `pyarrow` versions (10, 11) and `vds3` v0.8 on macOS Ventura 13.1 with Python 3.9.16.

All other common file types (CSV, JSON, etc.) are working fine.

**Comment by ajkerrigan** [comment]
Apologies I missed this until just the other day. This looks like an issue with VisiData's parquet loader which I'm addressing in https://github.com/saulpw/visidata/pull/1913.

It's also worth noting that in the time since you opened this, we've moved S3 support into VisiData core. That _should_ make things a bit more straightforward, and avoid some "whose problem is this?" if something in the S3 sphere is busted.

Thanks for the report in any case, it'll be a good thing to have fixed! :beers:
